services:
  sql-server:
    image: mcr.microsoft.com/mssql/server
    container_name: sql-server-container
    environment:
      SA_PASSWORD: 123qweASD.
      ACCEPT_EULA: Y
      MSSQL_ENCRYPT: 0
      MSSQL_PID: developer
      MSSQL_TCP_PORT: 1433
    ports:
      - "1433:1433"
